"""
数字图像处理教学平台 —— 理论数据库
为每个操作提供：概念定义、数学公式、算法步骤、关键参数说明
"""

THEORY_DETAIL = {}

def _reg(op_id, name, chapter, concept, formulas, steps, params_desc):
    THEORY_DETAIL[op_id] = {
        "name": name, "chapter": chapter,
        "concept": concept, "formulas": formulas,
        "steps": steps, "params_desc": params_desc,
    }

ALL_OPERATIONS = ["sampling_demo", "quantization_demo", "resolution_compare", "pixel_neighbors", "distance_metrics", "interpolation_demo", "image_inversion", "log_transform", "contrast_stretch", "histogram_equalization", "clahe", "gamma_correction", "median_blur", "gaussian_blur", "bilateral_filter", "laplacian", "unsharp_mask", "sobel_sharpen", "ideal_lowpass", "ideal_highpass", "butterworth_lowpass", "butterworth_highpass", "gaussian_lowpass", "gaussian_highpass", "bandpass_filter", "gaussian_noise", "sp_noise", "mean_filter_restore", "median_restore", "nlm_denoise", "wiener_filter", "sobel", "canny", "rgb_split", "rgb_to_hsv", "hue_adjust", "saturation_adjust", "brightness_adjust", "color_balance", "pseudo_color", "color_hist_eq", "gaussian_pyramid", "laplacian_pyramid", "pyramid_blend", "dwt_denoise", "dwt_edge_enhance", "dct_visualize", "jpeg_simulate", "jpeg_compare", "binary_rle", "binary_huffman", "erosion_dilation", "open_close", "morph_gradient", "tophat", "blackhat", "skeletonize", "otsu_threshold", "adaptive_threshold", "kmeans_segment", "mean_shift_segment", "watershed", "grabcut", "contour_extract", "convex_hull", "min_enclosing", "contour_approx", "hu_moments", "shape_match", "fourier_descriptor", "template_matching", "hough_lines", "hough_circles", "corner_harris", "sift_features", "hog_features", "prewitt", "roberts", "region_growing"]
OPERATION_NAMES = {"sampling_demo": "采样过程演示", "quantization_demo": "量化过程演示", "resolution_compare": "空间分辨率对比", "pixel_neighbors": "像素邻域可视化", "distance_metrics": "距离度量演示", "interpolation_demo": "图像插值对比", "image_inversion": "图像反转", "log_transform": "对数变换", "contrast_stretch": "对比度拉伸", "histogram_equalization": "直方图均衡化", "clahe": "自适应直方图均衡(CLAHE)", "gamma_correction": "伽马校正", "median_blur": "中值滤波", "gaussian_blur": "高斯滤波", "bilateral_filter": "双边滤波", "laplacian": "拉普拉斯锐化", "unsharp_mask": "USM锐化", "sobel_sharpen": "Sobel锐化", "ideal_lowpass": "理想低通滤波", "ideal_highpass": "理想高通滤波", "butterworth_lowpass": "巴特沃斯低通滤波", "butterworth_highpass": "巴特沃斯高通滤波", "gaussian_lowpass": "高斯低通滤波", "gaussian_highpass": "高斯高通滤波", "bandpass_filter": "带通滤波", "gaussian_noise": "添加高斯噪声", "sp_noise": "添加椒盐噪声", "mean_filter_restore": "均值滤波去噪", "median_restore": "中值滤波去噪", "nlm_denoise": "非局部均值去噪(NLM)", "wiener_filter": "维纳滤波复原", "sobel": "Sobel边缘检测", "canny": "Canny边缘检测", "rgb_split": "RGB通道分离", "rgb_to_hsv": "RGB→HSV转换", "hue_adjust": "色调调整", "saturation_adjust": "饱和度调整", "brightness_adjust": "亮度调整", "color_balance": "色彩平衡调整", "pseudo_color": "假彩色增强", "color_hist_eq": "彩色直方图均衡化", "gaussian_pyramid": "高斯金字塔", "laplacian_pyramid": "拉普拉斯金字塔", "pyramid_blend": "多分辨率融合", "dwt_denoise": "离散小波降噪", "dwt_edge_enhance": "小波边缘增强", "dct_visualize": "DCT变换可视化", "jpeg_simulate": "JPEG压缩模拟", "jpeg_compare": "压缩质量对比", "binary_rle": "二值化与游程编码", "binary_huffman": "哈夫曼编码模拟", "erosion_dilation": "腐蚀与膨胀", "open_close": "开运算与闭运算", "morph_gradient": "形态学梯度", "tophat": "顶帽变换", "blackhat": "黑帽变换", "skeletonize": "骨架提取", "otsu_threshold": "Otsu阈值分割", "adaptive_threshold": "自适应阈值分割", "kmeans_segment": "K-means聚类分割", "mean_shift_segment": "Mean Shift分割", "watershed": "分水岭算法", "grabcut": "GrabCut分割", "contour_extract": "轮廓提取", "convex_hull": "凸包检测", "min_enclosing": "最小外接矩形", "contour_approx": "轮廓近似", "hu_moments": "Hu矩特征", "shape_match": "形状匹配", "fourier_descriptor": "傅里叶描述子", "template_matching": "模板匹配", "hough_lines": "霍夫线检测", "hough_circles": "霍夫圆检测", "corner_harris": "Harris角点检测", "sift_features": "SIFT特征检测", "hog_features": "HOG特征提取", "prewitt": "Prewitt边缘检测", "roberts": "Roberts边缘检测", "region_growing": "区域生长分割"}
OPERATION_CHAPTERS = {"sampling_demo": 1, "quantization_demo": 1, "resolution_compare": 1, "pixel_neighbors": 1, "distance_metrics": 1, "interpolation_demo": 1, "image_inversion": 3, "log_transform": 3, "contrast_stretch": 3, "histogram_equalization": 3, "clahe": 3, "gamma_correction": 3, "median_blur": 3, "gaussian_blur": 3, "bilateral_filter": 3, "laplacian": 3, "unsharp_mask": 3, "sobel_sharpen": 3, "ideal_lowpass": 4, "ideal_highpass": 4, "butterworth_lowpass": 4, "butterworth_highpass": 4, "gaussian_lowpass": 4, "gaussian_highpass": 4, "bandpass_filter": 4, "gaussian_noise": 5, "sp_noise": 5, "mean_filter_restore": 5, "median_restore": 5, "nlm_denoise": 5, "wiener_filter": 5, "sobel": 5, "canny": 5, "rgb_split": 6, "rgb_to_hsv": 6, "hue_adjust": 6, "saturation_adjust": 6, "brightness_adjust": 6, "color_balance": 6, "pseudo_color": 6, "color_hist_eq": 6, "gaussian_pyramid": 7, "laplacian_pyramid": 7, "pyramid_blend": 7, "dwt_denoise": 7, "dwt_edge_enhance": 7, "dct_visualize": 8, "jpeg_simulate": 8, "jpeg_compare": 8, "binary_rle": 8, "binary_huffman": 8, "erosion_dilation": 9, "open_close": 9, "morph_gradient": 9, "tophat": 9, "blackhat": 9, "skeletonize": 9, "otsu_threshold": 10, "adaptive_threshold": 10, "kmeans_segment": 10, "mean_shift_segment": 10, "watershed": 10, "grabcut": 10, "contour_extract": 11, "convex_hull": 11, "min_enclosing": 11, "contour_approx": 11, "hu_moments": 11, "shape_match": 11, "fourier_descriptor": 11, "template_matching": 12, "hough_lines": 12, "hough_circles": 12, "corner_harris": 12, "sift_features": 12, "hog_features": 12, "prewitt": 12, "roberts": 12, "region_growing": 10}
